version: "3"

services:
  development:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      POSTGRES_URL: postgresql://ioda:password@localhost:5432/ioda

  db:
    image: postgres:16
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ioda
      POSTGRES_USER: ioda
      POSTGRES_PASSWORD: password

volumes:
  db: